"""project model and locality changes

Revision ID: 264ad1b6a6ac
Revises: 568367987c0c
Create Date: 2025-07-31 00:52:42.594450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264ad1b6a6ac'
down_revision: Union[str, Sequence[str], None] = '568367987c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nearby_landmarks', sa.Column('icon_url', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('project_size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_size')
    op.drop_column('nearby_landmarks', 'icon_url')
    # ### end Alembic commands ###
