"""initial projects and developer table

Revision ID: 79764abb481a
Revises: b59a18e63047
Create Date: 2025-07-13 03:42:45.731838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79764abb481a'
down_revision: Union[str, Sequence[str], None] = 'b59a18e63047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_units', sa.Column('subcategory', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_units', 'subcategory')
    # ### end Alembic commands ###
