"""initial projects and developer table

Revision ID: a5760dc5c91d
Revises: b01a1ab3bc73
Create Date: 2025-07-13 03:02:54.722454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5760dc5c91d'
down_revision: Union[str, Sequence[str], None] = 'b01a1ab3bc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('rera_number', sa.String(), nullable=True),
    sa.Column('locality_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rera_number')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('locality_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('badges', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('possession_date', sa.Date(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('rera_number', sa.String(), nullable=True),
    sa.Column('starting_price', sa.DECIMAL(), nullable=True),
    sa.Column('price_range', sa.JSON(), nullable=True),
    sa.Column('commission_structure', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('locality_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('size_sqft', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('available_units', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resale_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('project_unit_id', sa.UUID(), nullable=False),
    sa.Column('locality_id', sa.UUID(), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=True),
    sa.Column('size_sqft', sa.Integer(), nullable=True),
    sa.Column('asking_price', sa.DECIMAL(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('possession_status', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.ForeignKeyConstraint(['project_unit_id'], ['project_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resale_listings')
    op.drop_table('project_units')
    op.drop_table('project_media')
    op.drop_table('projects')
    op.drop_table('developers')
    # ### end Alembic commands ###
