"""initial projects and developer table

Revision ID: b59a18e63047
Revises: a5760dc5c91d
Create Date: 2025-07-13 03:10:36.342641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59a18e63047'
down_revision: Union[str, Sequence[str], None] = 'a5760dc5c91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_media', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_media', 'is_featured')
    # ### end Alembic commands ###
