"""project model size unit

Revision ID: c5fdf39861cd
Revises: 264ad1b6a6ac
Create Date: 2025-07-31 01:12:52.719277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fdf39861cd'
down_revision: Union[str, Sequence[str], None] = '264ad1b6a6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_size_unit', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_size_unit')
    # ### end Alembic commands ###
