"""is_active is_delete

Revision ID: f02ff776f034
Revises: 79764abb481a
Create Date: 2025-07-19 20:18:50.712065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02ff776f034'
down_revision: Union[str, Sequence[str], None] = '79764abb481a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('developers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('developers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('project_media', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('project_media', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('project_units', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('project_units', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('project_units', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_units', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('resale_listings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('resale_listings', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('user_addresses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_addresses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'is_deleted')
    op.drop_column('user_preferences', 'is_active')
    op.drop_column('user_addresses', 'is_deleted')
    op.drop_column('user_addresses', 'is_active')
    op.drop_column('resale_listings', 'is_deleted')
    op.drop_column('resale_listings', 'is_active')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'is_active')
    op.drop_column('project_units', 'updated_at')
    op.drop_column('project_units', 'created_at')
    op.drop_column('project_units', 'is_deleted')
    op.drop_column('project_units', 'is_active')
    op.drop_column('project_media', 'is_deleted')
    op.drop_column('project_media', 'is_active')
    op.drop_column('developers', 'is_deleted')
    op.drop_column('developers', 'is_active')
    op.drop_column('companies', 'is_deleted')
    op.drop_column('companies', 'is_active')
    # ### end Alembic commands ###
